dist: focal

language: 
  - go
  
go:
  - 1.13.x
  - 1.15.x
docker:
  - 1.19.3
os:
  - linux

arch:
  - arm64 
  - amd64
  
sudo: true

addons:
  apt:
    update: true
  hosts:
    - node1
    - node2
    - node3

script: 
  - sudo apt install golang
  - sudo apt install docker
  - make -j16
